apiVersion: v1
kind: Pod
metadata:
  name: nginx-new-node1
spec:
  containers:
  - name: nginx
    image: nginx:1.13.12
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: k8s-new-node1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2-new-node1
spec:
  containers:
  - name: nginx
    image: nginx:1.13.12
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: k8s-new-node1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-new-node2
spec:
  containers:
  - name: nginx
    image: nginx:1.13.12
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: k8s-new-node2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2-new-node2
spec:
  containers:
  - name: nginx
    image: nginx:1.13.12
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: k8s-new-node2
